### ISSUE TITLE
Releases `5.7.0` and `5.7.1` are preventing multiple managers within the same class

### ISSUE THREAD

**Issue by phansys** [mcfedr/queue-manager-bundle#5]
I'm opening this issue to track the problem exposed at https://github.com/mcfedr/queue-manager-bundle/commit/76cc5f17ccb25131e8d80e743c06b0cca3faad26#commitcomment-25509822.

**Comment by mcfedr** [comment]
Ok, looks like i didn't think though all the versions of this affects things. Thanks for investigating this.

Looks like i need to make the change to just give the first manager of each type the 'class' name in the container, and additional ones will have to get the old name. I'll try and work on a fix for this asap.

**Comment by mcfedr** [comment]
Should be fixed in 5.7.2, please let me know as I am not using this setup in a production environment, but I have added tests.

Now the first manager is given the class name service name, and further ones a different name.

Also, some versions of Symfony didn't let you have multiple commands with the same class, this was fixed in 3.3 - https://github.com/symfony/symfony/pull/22120

**Comment by phansys** [comment]
Great @mcfedr, I've updated my constraint to `"mcfedr/queue-manager-bundle": "^5.2,<5.7.0||>=5.7.2"`, it works as expected.
Thank you very much.
